### ISSUE TITLE
[Support request] Building instructions

### ISSUE THREAD

**Issue by pejakm** [jackpf/ApkDownloader#23]
Hi! Coud you please provide building instructions? Or a gradle build.properties? Thanks.

**Comment by jackpf** [comment]
Hi, it should build just by importing it into android developer tools, I've not been using gradle. Let me know if there are any problems with it though

**Comment by pejakm** [comment]
Is there anywhere a tutorial on how to do this correctly? I have imported ApkDownloader into Eclipse, but I can't (and don't know how to) compile it, and Eclipse also showing 100 errors:

https://mediacru.sh/asc6GSg6jGNU

**Comment by jackpf** [comment]
Hmm, what's the error on AndroidManifest.xml? Have you got the kitkat api (api level 19) downloaded with android sdk manager?

**Comment by pejakm** [comment]
Yes, I have API 19, but, never mind, I gave up on building it. :) Thanks for your help, I appreciate it.
